#
# Building for BDring new 6x board
#

#
# NOTE: PlatformIO support is provided by the community and platformio.ini is
# not maintained or tested by the repo owner.
# Please submit a PR with bug fixes and enhancments.
#

[platformio]
src_dir = main
include_dir = main

[wifi_networking]
build_flags =

[env:esp32doit-devkit-v1]
platform = espressif32 @ ~4.0.0
framework = espidf
board = esp32doit-devkit-v1
board_build.partitions = partitions.csv

board_build.embed_files =
    main/embedded/favicon.ico
    main/embedded/ap_login.html
    main/embedded/index.html.gz

build_flags =
    -Wimplicit-fallthrough=1
    -Wno-missing-field-initializers
    -Wno-maybe-uninitialized
    -Wno-stringop-truncation
    -DCONFIG_IDF_TARGET_ESP32=1
    ; -DY_AUTO_SQUARE=1
    ; -DDRIVER_SPINDLE_PWM_ENABLE=1
    ; -DSDCARD_ENABLE=2
    -DNETWORK_STA_HOSTNAME=grblHAL_6x
    -DPROBE_ENABLE=1
    -DPROBE_PIN=GPIO_NUM_2

monitor_speed=115200

lib_compat_mode = off

[env:ooznest-cnc]
platform = espressif32 @ 5.3.0  ; This forces ESP-IDF v4.4.x
framework = espidf
board = esp32-s3-devkitc-1
board_build.partitions = partitions.csv

board_build.embed_files =
    main/embedded/favicon.ico
    main/embedded/ap_login.html
    main/embedded/index.html.gz

board_build.cmake_extra_args =
    ; -DETHERNET_ENABLE=1
    ; -DSDKCONFIG_DEFAULTS="sdkconfig.ooznest-cnc"

build_flags =
    -DCONFIG_IDF_TARGET_ESP32S3
    -DBOARD_OOZNEST_CNC
    -DN_SPINDLE=3
    -DSPINDLE0_ENABLE=6
    -DSPINDLE1_ENABLE=12
    -DSPINDLE2_ENABLE=14
    -DY_AUTO_SQUARE=1
    -DMODBUS_ENABLE=1
    -DRGB_LED_ENABLE=2
    -DUSB_SERIAL_CDC=1
    -DWIFI_ENABLE=1
    ; -DETHERNET_ENABLE=1
    -DWEBUI_ENABLE=3
    -DHTTP_ENABLE=1
    -DPROBE_ENABLE=1
    -DTOOLSETTER_ENABLE=1
    -DMACROS_ENABLE=1
    -DN_MACROS=1
    ; -DSTATUS_LIGHT_ENABLE=2
    -DEVENTOUT_ENABLE=1
    -DSDCARD_ENABLE=2
    -DNETWORKING_ENABLE=1
    -DTELNET_ENABLE=1
    -DWEBSOCKET_ENABLE=1
    -DFTP_ENABLE=1
    -DLITTLEFS_ENABLE=1
    -DCONTROL_ENABLE=0
    ; -DCONFIG_ESP_CONSOLE_UART_NONE=1
    ; -DCONFIG_ESP_CONSOLE_USB_CDC=1

board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_upload.flash_size = 4MB
monitor_speed=115200
